// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);

void updatesubjects(lv_obj_t *label, const char *text);

extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_yearName;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_className;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_textR3C1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_textR1C1;
extern lv_obj_t * ui_textR2C1;
extern lv_obj_t * ui_textR4C1;
extern lv_obj_t * ui_textR5C1;
extern lv_obj_t * ui_textR1C2;
extern lv_obj_t * ui_textR2C2;
extern lv_obj_t * ui_textR3C2;
extern lv_obj_t * ui_textR4C2;
extern lv_obj_t * ui_textR5C2;
extern lv_obj_t * ui_textR1C3;
extern lv_obj_t * ui_textR2C3;
extern lv_obj_t * ui_textR3C3;
extern lv_obj_t * ui_textR4C3;
extern lv_obj_t * ui_textR5C3;
extern lv_obj_t * ui_textR1C4;
extern lv_obj_t * ui_textR2C4;
extern lv_obj_t * ui_textR3C4;
extern lv_obj_t * ui_textR4C4;
extern lv_obj_t * ui_textR5C4;
extern lv_obj_t * ui_textR1C5;
extern lv_obj_t * ui_textR2C5;
extern lv_obj_t * ui_textR3C5;
extern lv_obj_t * ui_textR4C5;
extern lv_obj_t * ui_textR5C5;
extern lv_obj_t * ui_textR1C6;
extern lv_obj_t * ui_textR2C6;
extern lv_obj_t * ui_textR3C6;
extern lv_obj_t * ui_textR4C6;
extern lv_obj_t * ui_textR5C6;
extern lv_obj_t * ui_textR1C7;
extern lv_obj_t * ui_textR2C7;
extern lv_obj_t * ui_textR3C7;
extern lv_obj_t * ui_textR4C7;
extern lv_obj_t * ui_textR5C7;
extern lv_obj_t * ui_nextBtn;
extern lv_obj_t * ui_countText;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_privBtn;
extern lv_obj_t * ui_countText1;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
