// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_yearName;
lv_obj_t * ui_Label18;
lv_obj_t * ui_className;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_textR3C1;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_teacher1name;
lv_obj_t * ui_teacher2name;
lv_obj_t * ui_textR1C1;
lv_obj_t * ui_textR2C1;
lv_obj_t * ui_textR4C1;
lv_obj_t * ui_textR5C1;
lv_obj_t * ui_textR1C2;
lv_obj_t * ui_textR2C2;
lv_obj_t * ui_textR3C2;
lv_obj_t * ui_textR4C2;
lv_obj_t * ui_textR5C2;
lv_obj_t * ui_textR1C3;
lv_obj_t * ui_textR2C3;
lv_obj_t * ui_textR3C3;
lv_obj_t * ui_textR4C3;
lv_obj_t * ui_textR5C3;
lv_obj_t * ui_textR1C4;
lv_obj_t * ui_textR2C4;
lv_obj_t * ui_textR3C4;
lv_obj_t * ui_textR4C4;
lv_obj_t * ui_textR5C4;
lv_obj_t * ui_textR1C5;
lv_obj_t * ui_textR2C5;
lv_obj_t * ui_textR3C5;
lv_obj_t * ui_textR4C5;
lv_obj_t * ui_textR5C5;
lv_obj_t * ui_textR1C6;
lv_obj_t * ui_textR2C6;
lv_obj_t * ui_textR3C6;
lv_obj_t * ui_textR4C6;
lv_obj_t * ui_textR5C6;
lv_obj_t * ui_textR1C7;
lv_obj_t * ui_textR2C7;
lv_obj_t * ui_textR3C7;
lv_obj_t * ui_textR4C7;
lv_obj_t * ui_textR5C7;
lv_obj_t * ui_nextBtn;
lv_obj_t * ui_countText;
lv_obj_t * ui_Label3;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
