// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -2);
    lv_obj_set_y(ui_Label1, -104);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Department of Electrical Engineering");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -2);
    lv_obj_set_y(ui_Label2, -121);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "VIVA INSTITUTE OF TECHNOLOGY");

    ui_yearName = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_yearName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_yearName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_yearName, -53);
    lv_obj_set_y(ui_yearName, -79);
    lv_obj_set_align(ui_yearName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_yearName, "SECOND");
    lv_obj_set_style_text_font(ui_yearName, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -193);
    lv_obj_set_y(ui_Label18, -104);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Class Room");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_className = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_className, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_className, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_className, -195);
    lv_obj_set_y(ui_className, -88);
    lv_obj_set_align(ui_className, LV_ALIGN_CENTER);
    lv_label_set_text(ui_className, "B 105");
    lv_obj_set_style_text_font(ui_className, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 1);
    lv_obj_set_y(ui_Label17, 126);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17,
                      "Vishnu Waman Thakur Charitable Trust's | Shirgaon, Virar (E), Taluka-Vasai, District-Palghar, 401305, Maharashtra");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 463);
    lv_obj_set_height(ui_Panel1, 185);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 25);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -208);
    lv_obj_set_y(ui_Label4, -77);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Time\nDay");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label4, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -158);
    lv_obj_set_y(ui_Label5, -77);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -99);
    lv_obj_set_y(ui_Label6, -77);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label6, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -37);
    lv_obj_set_y(ui_Label7, -77);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label7, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 29);
    lv_obj_set_y(ui_Label8, -77);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label8, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 88);
    lv_obj_set_y(ui_Label9, -77);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label9, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 146);
    lv_obj_set_y(ui_Label10, -77);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label10, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 200);
    lv_obj_set_y(ui_Label11, -77);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "8:45 am\n9:45 am");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label11, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -209);
    lv_obj_set_y(ui_Label12, -44);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Mon");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C1, -157);
    lv_obj_set_y(ui_textR3C1, -1);
    lv_obj_set_align(ui_textR3C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C1, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -208);
    lv_obj_set_y(ui_Label13, -22);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Tue");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -211);
    lv_obj_set_y(ui_Label14, -1);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Wed");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -210);
    lv_obj_set_y(ui_Label15, 21);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Thu");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -208);
    lv_obj_set_y(ui_Label16, 43);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Fri");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_teacher1name = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_teacher1name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_teacher1name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_teacher1name, -5);
    lv_obj_set_y(ui_teacher1name, 69);
    lv_obj_set_align(ui_teacher1name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_teacher1name, "Prof. SAPNA GEHLOT ( B1 ), Prof. AMIT VISHWAKARMA ( B2 ) MENTOR");
    lv_obj_set_style_text_font(ui_teacher1name, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_teacher2name = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_teacher2name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_teacher2name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_teacher2name, -5);
    lv_obj_set_y(ui_teacher2name, 83);
    lv_obj_set_align(ui_teacher2name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_teacher2name, "Prof. SAPNA GEHLOT ( B1 ), Prof. AMIT VISHWAKARMA ( B2 ) MENTOR");
    lv_obj_set_style_text_font(ui_teacher2name, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C1, -157);
    lv_obj_set_y(ui_textR1C1, -45);
    lv_obj_set_align(ui_textR1C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C1, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C1, -157);
    lv_obj_set_y(ui_textR2C1, -22);
    lv_obj_set_align(ui_textR2C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C1, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C1, -157);
    lv_obj_set_y(ui_textR4C1, 21);
    lv_obj_set_align(ui_textR4C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C1, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C1, -158);
    lv_obj_set_y(ui_textR5C1, 42);
    lv_obj_set_align(ui_textR5C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C1, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C2, -100);
    lv_obj_set_y(ui_textR1C2, -45);
    lv_obj_set_align(ui_textR1C2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C2, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C2, -100);
    lv_obj_set_y(ui_textR2C2, -22);
    lv_obj_set_align(ui_textR2C2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C2, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C2, -100);
    lv_obj_set_y(ui_textR3C2, -1);
    lv_obj_set_align(ui_textR3C2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C2, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C2, -100);
    lv_obj_set_y(ui_textR4C2, 21);
    lv_obj_set_align(ui_textR4C2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C2, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C2, -100);
    lv_obj_set_y(ui_textR5C2, 42);
    lv_obj_set_align(ui_textR5C2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C2, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C3, -39);
    lv_obj_set_y(ui_textR1C3, -45);
    lv_obj_set_align(ui_textR1C3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C3, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C3, -39);
    lv_obj_set_y(ui_textR2C3, -22);
    lv_obj_set_align(ui_textR2C3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C3, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C3, -39);
    lv_obj_set_y(ui_textR3C3, -1);
    lv_obj_set_align(ui_textR3C3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C3, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C3, -39);
    lv_obj_set_y(ui_textR4C3, 21);
    lv_obj_set_align(ui_textR4C3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C3, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C3, -39);
    lv_obj_set_y(ui_textR5C3, 43);
    lv_obj_set_align(ui_textR5C3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C3, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C4, 29);
    lv_obj_set_y(ui_textR1C4, -45);
    lv_obj_set_align(ui_textR1C4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C4, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C4, 29);
    lv_obj_set_y(ui_textR2C4, -23);
    lv_obj_set_align(ui_textR2C4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C4, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C4, 29);
    lv_obj_set_y(ui_textR3C4, -1);
    lv_obj_set_align(ui_textR3C4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C4, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C4, 28);
    lv_obj_set_y(ui_textR4C4, 22);
    lv_obj_set_align(ui_textR4C4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C4, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C4, 28);
    lv_obj_set_y(ui_textR5C4, 44);
    lv_obj_set_align(ui_textR5C4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C4, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C5, 87);
    lv_obj_set_y(ui_textR1C5, -45);
    lv_obj_set_align(ui_textR1C5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C5, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C5, 87);
    lv_obj_set_y(ui_textR2C5, -23);
    lv_obj_set_align(ui_textR2C5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C5, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C5, 87);
    lv_obj_set_y(ui_textR3C5, 0);
    lv_obj_set_align(ui_textR3C5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C5, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C5, 87);
    lv_obj_set_y(ui_textR4C5, 21);
    lv_obj_set_align(ui_textR4C5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C5, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C5, 87);
    lv_obj_set_y(ui_textR5C5, 44);
    lv_obj_set_align(ui_textR5C5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C5, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C6, 146);
    lv_obj_set_y(ui_textR1C6, -44);
    lv_obj_set_align(ui_textR1C6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C6, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C6, 145);
    lv_obj_set_y(ui_textR2C6, -22);
    lv_obj_set_align(ui_textR2C6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C6, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C6, 145);
    lv_obj_set_y(ui_textR3C6, 1);
    lv_obj_set_align(ui_textR3C6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C6, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C6, 145);
    lv_obj_set_y(ui_textR4C6, 22);
    lv_obj_set_align(ui_textR4C6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C6, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C6 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C6, 145);
    lv_obj_set_y(ui_textR5C6, 43);
    lv_obj_set_align(ui_textR5C6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C6, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C6, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR1C7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR1C7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR1C7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR1C7, 199);
    lv_obj_set_y(ui_textR1C7, -45);
    lv_obj_set_align(ui_textR1C7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR1C7, "EACM-I");
    lv_obj_set_style_text_font(ui_textR1C7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR2C7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR2C7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR2C7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR2C7, 198);
    lv_obj_set_y(ui_textR2C7, -23);
    lv_obj_set_align(ui_textR2C7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR2C7, "EACM-I");
    lv_obj_set_style_text_font(ui_textR2C7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR3C7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR3C7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR3C7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR3C7, 199);
    lv_obj_set_y(ui_textR3C7, 1);
    lv_obj_set_align(ui_textR3C7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR3C7, "EACM-I");
    lv_obj_set_style_text_font(ui_textR3C7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR4C7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR4C7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR4C7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR4C7, 198);
    lv_obj_set_y(ui_textR4C7, 22);
    lv_obj_set_align(ui_textR4C7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR4C7, "EACM-I");
    lv_obj_set_style_text_font(ui_textR4C7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textR5C7 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textR5C7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textR5C7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textR5C7, 198);
    lv_obj_set_y(ui_textR5C7, 43);
    lv_obj_set_align(ui_textR5C7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textR5C7, "EACM-I");
    lv_obj_set_style_text_font(ui_textR5C7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_nextBtn, 57);
    lv_obj_set_height(ui_nextBtn, 32);
    lv_obj_set_x(ui_nextBtn, 200);
    lv_obj_set_y(ui_nextBtn, -103);
    lv_obj_set_align(ui_nextBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nextBtn, lv_color_hex(0xC3F3F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nextBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_nextBtn, lv_color_hex(0x23E40D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_nextBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_dir(ui_nextBtn, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_nextBtn, lv_color_hex(0x69EB5B), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_nextBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_nextBtn, 20, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_nextBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_countText = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_countText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_countText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_countText, 199);
    lv_obj_set_y(ui_countText, -103);
    lv_obj_set_align(ui_countText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_countText, "Next");
    lv_obj_set_style_text_font(ui_countText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 46);
    lv_obj_set_y(ui_Label3, -79);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Year Engineering");

    ui_privBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_privBtn, 51);
    lv_obj_set_height(ui_privBtn, 28);
    lv_obj_set_x(ui_privBtn, 202);
    lv_obj_set_y(ui_privBtn, 100);
    lv_obj_set_align(ui_privBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_privBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_privBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_privBtn, lv_color_hex(0xFB8C9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_privBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_countText1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_countText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_countText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_countText1, 201);
    lv_obj_set_y(ui_countText1, 100);
    lv_obj_set_align(ui_countText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_countText1, "Next");
    lv_obj_set_style_text_font(ui_countText1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

}


void updatesubjects(lv_obj_t *label, const char *text) {
    lv_label_set_text(label, text);
}